### ISSUE TITLE
Questions and Suggestions

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#21] opened 2020-05-01 03:39 UTC
Now in both variants of syntax css punctuation are too pale and bad readable. Here are some examples:
![ex1](https://user-images.githubusercontent.com/58516282/80779951-de959180-8b75-11ea-92b5-930337056744.png)
![ex2](https://user-images.githubusercontent.com/58516282/80779956-e3f2dc00-8b75-11ea-87e8-9c749b54b36c.png)
![ex3](https://user-images.githubusercontent.com/58516282/80779980-f240f800-8b75-11ea-89f3-63144258227f.png)
Probably use white color instead in this scope? For examples color of html simple text.
`			"scope": "punctuation.definition.entity.css, punctuation.separator.key-value.css, punctuation.terminator.rule.css, punctuation.separator.list.comma.css",
			"settings": {
				"foreground": "#928374"
			}`

**Comment by sainnhe** [comment] 2020-05-01 06:11
I must admit that this is just my personal preference, I prefer to use grey as the foreground color of some accessors and separators. Also, I prefer to use minimal highlighting and that's why the `gruvboxMaterial.colorfulSyntax` option is disabled by default.

Maybe you can fork this repository and maintain it by yourself. It's also very encouraged to do so, the code has been well organized and should be very easy to maintain.

**Comment by Z4RX** [comment] 2020-05-01 06:17
I just changed it in my settings and here are screens just to compare with base variant.
![ex4](https://user-images.githubusercontent.com/58516282/80786460-65edff80-8b8c-11ea-903e-b817d09d2f25.png)
![ex5](https://user-images.githubusercontent.com/58516282/80786465-6ab2b380-8b8c-11ea-9db1-7101682c011f.png)

Huge thx for Your great work. This theme is rly cool and comfortable

**Comment by Z4RX** [comment] 2020-05-01 06:25
And one more moment. In base color setup in terminal there is 1 issue.
some parts of git commands like this are almost the same as a background color
![image](https://user-images.githubusercontent.com/58516282/80786740-34c1ff00-8b8d-11ea-8f73-8f9bb1a70c09.png)
I override it this way: 
`  "workbench.colorCustomizations": {
    "terminal.ansiBrightBlack": "#928374",
  },`
![image](https://user-images.githubusercontent.com/58516282/80786860-87032000-8b8d-11ea-9b89-72da393e86be.png)
Probably this parameter should be overriden in theme, so look at this pls

**Comment by sainnhe** [comment] 2020-05-01 08:58
Should be fixed via be4687e.

I'll release a new version after I finished semantic highlighting.

**Comment by Z4RX** [comment] 2020-05-01 21:24
Now _scss_ and _css_ pictuation are not the same
this change 
`"scope": "punctuation.definition.entity.scss, punctuation.separator.key-value.scss, punctuation.terminator.rule.scss, punctuation.separator.list.comma.scss",
       "settings": {
        "foreground": "#928374"
       }` of this scope 
`"scope": "punctuation.definition.keyword.scss, punctuation.separator.key-value.scss",
			"settings": {
				"foreground": "#928374"
			}` 
will chage the situation.
before:
![ex3](https://user-images.githubusercontent.com/58516282/80842749-1ac70180-8c0b-11ea-87ab-a934c0f3ab9d.png)
after:
![ex6](https://user-images.githubusercontent.com/58516282/80842762-21ee0f80-8c0b-11ea-94a7-e8b4d7f68c83.png)

**Comment by sainnhe** [comment] 2020-05-02 00:18
Thanks very much, should be fixed via 9637ec0.

**Comment by sainnhe** [comment] 2020-05-02 08:18
v6.2.0 is now available on the marketplace.

**Comment by Z4RX** [comment] 2020-05-02 09:24
Now js separators (with and without semantic) are orange. I looked new scopes and it looks like they should be grey. But anyway it doesn't look bad just a bit unusual.
Example:
![ex7](https://user-images.githubusercontent.com/58516282/80860345-bee29400-8c6f-11ea-9496-0501c5b25ef3.png)

**Comment by sainnhe** [comment] 2020-05-02 10:06
Thanks for your feedback, I'll fix it later.

**Comment by sainnhe** [comment] 2020-05-03 10:28
I just tried it and cannot reproduce this.

![foo](https://user-images.githubusercontent.com/37491630/80911888-c38c7280-8d6b-11ea-897b-72b653eba24b.png)

**Comment by Z4RX** [comment] 2020-05-03 14:38
Idk, i don't have any customisation in json. even reload theme. semantic is off too
![ex8](https://user-images.githubusercontent.com/58516282/80916982-d2235b80-8d64-11ea-8ded-8305d8c8eaef.png)

**Comment by Z4RX** [comment] 2020-05-03 15:43
This extension modify a bit colorization
https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

**Comment by sainnhe** [comment] 2020-05-04 07:38
Should be fixed via 5f9d547.

**Comment by Z4RX** [comment] 2020-05-05 03:57
I think that minimap search result should be more contrast, now it's rly difficult to see the result.
Probable change for material palete: `"minimap.findMatchHighlight": "#68948a80",`
I used `merge.currentContentBackground` color.
Examples:
Original:
![image](https://user-images.githubusercontent.com/58516282/81033600-db174880-8e9c-11ea-8247-256ac8d3bd14.png)
After fix:
![image](https://user-images.githubusercontent.com/58516282/81033550-b6bb6c00-8e9c-11ea-9f3a-1a0c2d1a8cea.png)

**Comment by sainnhe** [comment] 2020-06-28 05:23
`#7daea3a0` means `#7daea3` with `a0` transparency, I think it might be better to use color code like `#7daea3c8`

**Comment by sainnhe** [comment] 2020-06-30 11:43
So I adjusted the contrast via 616fe09.

I'm going to close this issue because there have been too many discussions. If you have any other problems, open a new issue instead.

**Closed by sainnhe** 2020-06-30 11:43 UTC
Labels: discuss
