### ISSUE TITLE
More Readable Color for Function Call ? 

### ISSUE THREAD

**Issue by GulajavaMinistudio** [sainnhe/gruvbox-material-vscode#7] opened 2020-01-01 12:20 UTC
Hello, thanks for good theme. Recently, i try this theme in one of our project with Vue JS with Vue CLI in VS Code. But it resulted, green color for function name is not easy readable. You can take a look in this screenshot. 

This is for your Gruvbox Material Theme
![Screenshot_2020-01-01_19-12-56](https://user-images.githubusercontent.com/11639412/71641263-5b4d5780-2ccb-11ea-98f9-cbe9159a5082.png)

Compare it with other theme, such as Gruvbox Original
![Screenshot_2020-01-01_19-12-18](https://user-images.githubusercontent.com/11639412/71641270-73bd7200-2ccb-11ea-859b-58e9baf1c06b.png)

Or with Monokai Pro theme
![Screenshot_2020-01-01_19-13-53](https://user-images.githubusercontent.com/11639412/71641272-7c15ad00-2ccb-11ea-9098-6d447f4f517c.png)

As you can see, your theme with Green color for function name in "methods" in Vue Component look not good and not easy readable. Maybe you can change this color for more green or more vivid green color, so it easy readable ?

**Comment by sainnhe** [comment] 2020-01-01 13:58
I haven't optimize vue for this theme yet, I'll do that later.

**Comment by sainnhe** [comment] 2020-01-02 02:07
Which syntax highlighting extension are you using? I've tried both [jcbuisson.vue](https://marketplace.visualstudio.com/items?itemName=jcbuisson.vue) and [liuji-jim.vue](https://marketplace.visualstudio.com/items?itemName=liuji-jim.vue) but still cannot reproduce.

![demo1](https://user-images.githubusercontent.com/37491630/71649204-b6249480-2d47-11ea-8ce3-d99582707ae7.png)

**Comment by sainnhe** [comment] 2020-01-02 02:55
This issue may be duplicated with #6.

I have to say that I still keep my point, [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) is **very bad**. Microsoft has done a very great job on javascript syntax highlighting which is buildin in vscode, but this extension makes things terrible, I think not installing it is better than installing it.

I once considered setting gruvbox-material to conflict with this extension, but in the end I decided to remind users not to install this extension in the README.

Still, I compromised. A theme extension should do its best to be compatible with the syntax, no matter how bad this syntax extension is. I've basically optimized this extension via 326143d.

**Comment by GulajavaMinistudio** [comment] 2020-01-02 02:58
Oh  I'm sorry, I'm using Babel JavaScript syntax highlighting too. Maybe i should disabled it when using your theme. Thank you for workaround

**Comment by sainnhe** [comment] 2020-01-02 03:00
You don't need to disable it now, this problem should be fixed. You can update this theme and get it a try.

**Comment by GulajavaMinistudio** [comment] 2020-01-02 03:07
Thank you, i have been updated gruvbox material extension, and this works better than before when using in Vue JS Project. Now this theme is more readable color now. 

![Screenshot_2020-01-02_10-04-33](https://user-images.githubusercontent.com/11639412/71650278-6a71eb00-2d47-11ea-8df2-ecbdd1c7dc90.png)

You can close this issue, as it solved.

**Closed** 2020-01-02 03:11 UTC
